ChatApp/core/urls.py
from django.contrib import admin
from django.urls import path, include
from page import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",views.home_screen_view, name="home"),
    path("account/",include('account.urls')),
    path('admin/', admin.site.urls),
    path('friend/', include('friend.urls')),
    path('private-chat/', include('private_chat.urls')),
    
]
if settings.DEBUG:
    urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns  +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChatApp/private_chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.conf import settings

from notification.models import Notification

# Create your models here.

Account = get_user_model()

class PrivateChatRoom(models.Model):
    user1 = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='user2')
    connected_users = models.ManyToManyField(Account, blank=True, related_name="connected_users")
    is_active = models.BooleanField(default=True)

    # returns true if user is added to the connected_users list
    def connect_user(self, user):
        is_user_added = False
        if not user in self.connected_users.all():
            self.connected_users.add(user)
            is_user_added = True
        return is_user_added

    def disconnect_user(self, user):
        is_user_removed = False
        if user in self.connected_users.all():
            self.connected_users.remove(user)
            is_user_removed = True
        return is_user_removed

    def __str__(self):
        return f"A Chat between {self.user1} and {self.user2}"
    
    @property
    def group_name(self):
        """
        returns the channels group name that sockets shouls subscribe to so 
        they get sent messages as they are generated
        """
        return f"privateChatRoom-{self.id}"
    

class PrivateChatRoomMessageManager(models.Manager):
    def by_room(self, room):
        qs = PrivateChatRoomMessage.objects.filter(room=room).order_by("-timestamp")
        return qs

class PrivateChatRoomMessage(models.Model):
    # Chat message created by a user inside a room

    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    room = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField(unique=False, blank=False)

    objects = PrivateChatRoomMessageManager()

    def __str__(self) :
        return self.content
    

class UnreadPrivateChatRoomMessages(models.Model):
    room = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    most_recent_message = models.CharField(max_length=100, blank=True, null=True)
    reset_timestamp = models.DateTimeField()
    notifications = GenericRelation(Notification)

    def __str__(self):
        return f"Messages that {self.user.username} has not read yet."
    
    def save(self,*args, **kwargs):
        if not self.id: # if just created, add a timestamp. otherwise do not automatically change it.
            self.reset_timestamp = timezone.now()
        return super(UnreadPrivateChatRoomMessages, self).save(*args, **kwargs)
    
    # for determining what kind of object is associated with a notification
    @property
    def get_cname(self):
        return "UnreadPrivateChatRoomMessages"
    
    # Get the other user in the chatroom
    @property
    def get_other_user(self):
        if self.user == self.room.user1:
            return self.room.user2
        else:
            return self.room.user1
        
    
# signal
@receiver(post_save, sender=PrivateChatRoom)
def create_unread_private_chatroom_messages_obj(sender, instance, created, **kwargs):
    if created:
        unread_msg1 = UnreadPrivateChatRoomMessages(room=instance, user=instance.user1)
        unread_msg1.save()

        unread_msg2 = UnreadPrivateChatRoomMessages(room=instance, user=instance.user2)
        unread_msg2.save()

# when the unread message count increases, update the notification.
# if one does not exist, create one.(This should never happen)
@receiver(pre_save, sender=UnreadPrivateChatRoomMessages)
def increment_unread_msg_count(sender, instance, **kwargs):
    if instance.id is None:
        pass
    else:
        previous = UnreadPrivateChatRoomMessages.objects.get(id=instance.id)
        if previous.count < instance.count:
            content_type = ContentType.objects.get_for_model(instance)
            if instance.user == instance.room.user1:
                other_user = instance.room.user2
            else:
                other_user = instance.room.user1
            try:
                notification = Notification.objects.get(target=instance.user, content_type=content_type, object_id=instance.id)
                notification.verb = instance.most_recent_message
                notification.timestamp = timezone.now()
                notification.save()
            except Notification.DoesNotExist:
                instance.notifications.create(
                    target =instance.user,
                    from_user = other_user,
                    redirect_url = f"{settings.BASE_URL}/private-chat/?room_id={instance.room.id}",
                    verb = instance.most_recent_message,
                    content_type = content_type
                )

# if the unread message count decreases, it means the user joined the chat. so delete the notification.
@receiver(pre_save, sender=UnreadPrivateChatRoomMessages)
def remove_unread_msg_count_notification(sender, instance, **kwargs):
    if instance.id is None:
        pass
    else:
        previous = UnreadPrivateChatRoomMessages.objects.get(id=instance.id)
        if previous.count > instance.count:
            content_type = ContentType.objects.get_for_model(instance)
            try:
                notification = Notification.objects.get(target=instance.user, content_type=content_type, object_id=instance.id)
                notification.delete()
            except Notification.DoesNotExist:
                pass

ChatApp/templates/page/home.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
{% include "partials/_messages.html" %}

{% if debug %}
Public Chat
{% endif %}
<span class="page-number {% if not debug %}d-none{% endif %}" id="id_page_number">1</span>

<div class="container">
  <div class="card mt-3">
    <div class="card-header">
      <div class="d-flex flex-row justify-content-between">
        <h3>Open Space</h3>
        <div class="d-flex flex-row align-items-center">
          <span class="material-icons m-auto pe-1 connected-users-icon">person_outline</span>
          <span class="m-auto connected-users" id="id_connected_users"></span>
        </div>
      </div>
    </div>
    <div class="card-body p-1">
      <div class="d-flex flex-column">
        <div class="d-flex flex-row justify-content-center" id="id_chatroom_loading_spinner_container">
          <div class="spinner-border " id="id_chatroom_loading_spinner" role="status" style="display:none;">
            <span class="sr-only" >Loading...</span>
          </div>
        </div>
      
        <div class="d-flex chat-log  bg-light" id="id_chat_log"></div>
        <div class="d-flex chat-message-input-container">
          <textarea
            class="flex-grow-1 form-control chat-message-input"
            id="id_chat_message_input"></textarea>
          <button class="btn btn-primary chat-message-submit-button">
            <span id="id_chat_message_submit" class="material-icons">send </span>
          </button>
        </div>
      </div>
    </div>
    
  </div>
  
</div>

<!-- Client Error MODAL -->
<button 
  type="button" 
  id="id_trigger_client_error_modal"
  class="d-none btn btn-primary" 
  data-bs-toggle="modal" 
  data-bs-target="#id_client_error_modal">
</button>
<div 
  class="modal fade" 
  id="id_client_error_modal" 
  tabindex="-1"
  aria-labelledby="id_client_error_modalLabel"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Socket Client Error</h5>
        <button 
          type="button" 
          class="btn-close" 
          data-bs-dismiss="modal" 
          aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        <p id="id_client_error_modal_body">Something went wrong.</p>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          id="id_client_error_modal_close_btn">
          Close
        </button>
      </div>
    </div>
  </div>
</div>
<!-- Client Error MODAL -->

<!--Script-->
<script type="text/javascript">
  //ws:// or wss://
  var ws_scheme = window.location.protocal == "https:" ? "wss" : "ws";
  {% if debug_mode %}
    var ws_path = ws_scheme + "://" + window.location.host + "/public_chat/{{room_id}}/"    // development
  {% else %}
    var ws_path = ws_scheme + "://" + window.location.host + ":8001/public_chat/{{room_id}}/" // production
  {% endif %}

  var public_chat_socket = new WebSocket(ws_path)

  // handle incoming messages
  public_chat_socket.onmessage = function(message){
    console.log("Got chat websocket message: " + message.data)
    var data = JSON.parse(message.data)
    displayChatroomLoadingSpinner(data.display_progress_bar)
    // handle errors(ClientError)
    if(data.error){
      showClientErrorModal(data.message)
    }

    if(data.join){
      getRoomChatMessages()
      console.log(data.username + " join the room!")
    }
    // handle getting a message
    if(data.msg_type == 0){
      appendChatMessage(data, true, true)
    } 
    else if(data.msg_type == 1){
      setConnectedUsersCount(data.connected_user_count)
    }
    // send_messages_payload consumer side
    if (data.messages_payload){
      console.log("PAYLOAD")
      handleMessagesPayload(data.messages, data.new_page_number)
    }
  }

  public_chat_socket.addEventListener("open", function(e){
    console.log("public chat socket Open")
    // join the chat room
    if("{{request.user.is_authenticated}}"){
      public_chat_socket.send(JSON.stringify({
        "command":"join",
        "room": "{{room_id}}",
      }))
    }

  })

  public_chat_socket.onclose = function(e){
    console.log("public chat socket closed.")
  }

  public_chat_socket.onOpen = function(e){
    console.log("public chat socket onOpen", e)
  }

  public_chat_socket.onerror = function(e){
    console.log("public chat socket error: "+ e)
  }

  if(public_chat_socket.readyState == WebSocket.OPEN){
    console.log("public chat socket open")
  }
  else if(public_chat_socket.readyState == WebSocket.CONNECTING){
    console.log("public chat socket Connecting....")
  }

  document.getElementById("id_chat_message_input").focus()
  document.getElementById("id_chat_message_input").onkeyup = function(e){
    if(e.keycode == 13 && e.shiftkey){ // enter + return 
      // handled automatically by textarea
    }
    else if(e.keycode == 13 && !e.shiftkey){ // just enter
      document.getElementById("id_chat_message_submit").click()
    }
  }

  // send message
  document.getElementById("id_chat_message_submit").onclick = function(e){
    const messageInputDom = document.getElementById("id_chat_message_input")
    const message = messageInputDom.value
    public_chat_socket.send(JSON.stringify({
      "command": "send",
      "message": message,
      "room_id": "{{room_id}}",
    }))
    messageInputDom.value = ""
  }

  function setPageNumber(pageNumber){
    document.getElementById("id_page_number").innerHTML = pageNumber
  }

  function setPaginationExhausted(data){
    setPageNumber("-1")
  }

  // will execute command == "get_room_chat_message" in the consumer
  function getRoomChatMessages(){
    var pageNumber = document.getElementById("id_page_number").innerHTML
    if(pageNumber != "-1"){
      setPageNumber("-1") // qery is in progress
      public_chat_socket.send(JSON.stringify({
        "command": "get_room_chat_messages",
        "room_id": "{{room_id}}",
        "page_number": pageNumber
      }))
    }
  }
  // will "handle send_messages_payload" from the consumer
  function handleMessagesPayload(messages, new_page_number){
    if(messages != null && messages != "undefined" && messages != "None" ){
      setPageNumber(new_page_number)
      messages.forEach(function(message){
        appendChatMessage(message, true, false)
      })
    }
    else{
      setPaginationExhausted()
    }
  }

  var chatLog = document.getElementById("id_chat_log")
  chatLog.addEventListener("scroll", function(e){
    if((Math.abs(chatLog.scrollTop) + 2) >= (chatLog.scrollHeight - chatLog.offsetHeight)){
      getRoomChatMessages()
    }
  })

  function appendChatMessage(data, maintainPosition, isNewMessage){
    message = data['message']
    username = data['username']
    user_id = data['user_id']
    profile_image = data['profile_image']
    timestamp = data['natural_timestamp']
    msg_id = data['msg_id']

    var msg = message + "\n"
    var username = username + ": "
    createChatMessageElement(msg, msg_id, username, profile_image, user_id, timestamp, maintainPosition, isNewMessage)
  }

  function createChatMessageElement(msg, msg_id, username, profile_image, user_id, timestamp, maintainPosition, isNewMessage){
    var chatLog = document.getElementById("id_chat_log")

    var newMessageDiv = document.createElement("div")
    newMessageDiv.classList.add("d-flex")
    newMessageDiv.classList.add("flex-row")
    newMessageDiv.classList.add("message-container")

    var profileImage = document.createElement("img")
    profileImage.addEventListener("click", function(e){
      selectUser(user_id)
    })
    profileImage.classList.add("profile-image")
    profileImage.classList.add("rounded-circle")
    profileImage.classList.add("img-fluid")
    profileImage.src = "{% static 'images/default.jpg' %}"
    var profile_image_id = "id_profile_image_" + msg_id
    profileImage.id = profile_image_id
    {% comment %} profileImage.src = "profile_image" {% endcomment %}
    newMessageDiv.appendChild(profileImage)

    var div1 = document.createElement("div")
    div1.classList.add("d-flex")
    div1.classList.add("flex-column")

    var div2 = document.createElement("div")
    div2.classList.add("d-flex")
    div2.classList.add("flex-row")
    
    var usernameSpan = document.createElement("span")
    usernameSpan.addEventListener("click", function(e){
      selectUser(user_id)
    })
    usernameSpan.classList.add("username-span")
    usernameSpan.innerHTML= username
    div2.appendChild(usernameSpan)

    var timestampSpan = document.createElement("span")
    timestampSpan.innerHTML = timestamp
    timestampSpan.classList.add("timestamp-span")
    timestampSpan.classList.add("d-flex")
    timestampSpan.classList.add("align-items-center")
    div2.appendChild(timestampSpan)

    div1.appendChild(div2)

    var msgParagraph = document.createElement("p")
    msgParagraph.innerHTML = validateText(msg)
    msgParagraph.classList.add("msg-p")
    div1.appendChild(msgParagraph)

    newMessageDiv.appendChild(div1)

    if (isNewMessage){
      chatLog.insertBefore(newMessageDiv, chatLog.firstChild)
    }
    else{
      chatLog.appendChild(newMessageDiv)
    }
    if(!maintainPosition){
      chatLog.scrollTop = chatLog.scrollHeight
    }

    preloadImage(profile_image, profile_image_id)
  }

  function selectUser(user_id){
    var url = "{% url 'profile' user_id=5554899620024946 %}".replace("5554899620024946", user_id)
    var win = window.open(url,"_blank")
    win.focus()
  }
  
  function showClientErrorModal(message){
		document.getElementById("id_client_error_modal_body").innerHTML = message
		document.getElementById("id_trigger_client_error_modal").click()
	}

  function displayChatroomLoadingSpinner(isDisplayed){
    var spinner = document.getElementById("id_chatroom_loading_spinner")
    if(isDisplayed){
      spinner.style.display = "block"
    }
    else{
      spinner.style.display = "none"
    }
  }

  function setConnectedUsersCount(count){
    element = document.getElementById("id_connected_users")
    element.innerHTML = count
  }
</script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
<script type="text/javascript" src="{% static 'js/preloadImage.js' %}"></script>
{% endblock content %}